[fantasia]
# Interface IP to bind the server instance
host = "localhost"
# Port to bind on host
port = 8000
# Override `.env` file
env_file = ".env"

[postgres]
# Postgres superuser
user = "postgres"
# Postgres superuser password
password = "postgres"
# Postgres server host
host = "localhost"
# Postgres server port
port = 5432
# Postgres database name
database = "pgdb"

# See: https://docs.rs/sqlx/latest/sqlx/pool/struct.PoolOptions.html
[postgres.options]
test_before_acquire = true
acquire_timeout_seconds = 10
min_connections = 0
max_connections = 10
max_lifetime_seconds = 180
idle_timeout_seconds = 600
